name: 'ApiCov'
description: 'Collect API coverage data'
inputs:
  install_path:
    description: 'The directory where the build is installed'
    required: true
  root_path:
    description: 'The directory where the repo is cloned'
    required: true
outputs:
  apicov:
    description: "API coverage data"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Install Path
      run: echo "Install Dir $INPUT_PRJDIR."
      shell: bash
      env:
        INPUT_PRJDIR: ${{ inputs.directory }}

    - name: Root Path
      run: echo "Root Dir $INPUT_ROOTDIR."
      shell: bash
      env:
        INPUT_ROOTDIR: ${{ inputs.root }}

    - name: Random Number Generator
      id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Debug Action Directory
      run: |
        ls -R ${{ github.action_path }}
      shell: bash

    - name: Run APICov
      run: python3  ${{ github.action_path }}/src/apicov.py ${{ inputs.root }} ${{ inputs.directory }}
      shell: bash

