name: 'ApiCov'
description: 'Collect API coverage data'
inputs:
  directory:
    description: 'The directory where the build is installed'
    required: true
outputs:
  apicov:
    description: "API coverage data"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Set Greeting
      run: echo "Install Dir $INPUT_PRJDIR."
      shell: bash
      env:
        INPUT_PRJDIR: ${{ inputs.directory }}

    - name: Random Number Generator
      id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Run APICov
      run: python src/apicov.py "$GITHUB_WORKSPACE" "$INPUT_PRJDIR"
      shell: bash

