name: 'ApiCov'
description: 'Collect API coverage data'
inputs:
  install_path:
    description: 'The directory where the build is installed'
    required: true
  root_path:
    description: 'The directory where the repo is cloned'
    required: true
outputs:
  apicov:
    description: "API coverage data"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Install Path
      run: echo "Install Dir: ${{ inputs.install_path }}"
      shell: bash

    - name: Root Path
      run: echo "Root Dir: ${{ inputs.root_path }}"
      shell: bash

    - name: Random Number Generator
      id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Debug Action Path
      run: |
        echo "GitHub Action Path: ${{ github.action_path }}"
        ls -R "${{ github.action_path }}" || echo "Directory not found!"
      shell: bash

    - name: Run APICov
      run: python3 "${{ github.action_path }}/src/apicov.py" "${{ inputs.root_path }}" "${{ inputs.install_path }}"
      shell: bash


